In [ ]:
import numpy as np

text = "messi is the best"
words = text.split()


if len(words) != 4:
    print(f"Error: The text must contain exactly 4 words. This text has {len(words)} words.")
    exit()


vocab = sorted(list(set(words)))
vocab_size = len(vocab)

word_to_ix = {word: i for i, word in enumerate(vocab)}
ix_to_word = {i: word for i, word in enumerate(vocab)}

print(f"Vocabulary ({vocab_size} words): {vocab}")
print(f"Word to Index: {word_to_ix}")


def word_to_one_hot(word, vocab_size, word_to_ix_map):
    vector = np.zeros((vocab_size, 1))
    if word in word_to_ix_map:
        vector[word_to_ix_map[word]] = 1
    return vector


hidden_size = 5

W_xh = np.random.randn(hidden_size, vocab_size) * 0.1
W_hh = np.random.randn(hidden_size, hidden_size) * 0.1
W_ho = np.random.randn(vocab_size, hidden_size) * 0.1



input_words = words[:3]
target_word = words[3]

print(f"\nProcessing sequence: {' '.join(input_words)}")
print(f"Target word: '{target_word}'")

h = np.zeros((hidden_size, 1))
print(f"Initial hidden state:\n{h.T}\n")


word = input_words[0]
print(f"Processing word: '{word}'")
x = word_to_one_hot(word, vocab_size, word_to_ix)


h = np.dot(W_hh, h) + np.dot(W_xh, x)


print(f"Hidden state after '{word}':\n{h.T}\n")


word = input_words[1]
print(f"Processing word: '{word}'")
x = word_to_one_hot(word, vocab_size, word_to_ix)


h = np.dot(W_hh, h) + np.dot(W_xh, x)

print(f"Hidden state after '{word}':\n{h.T}\n")


word = input_words[2]
print(f"Processing word: '{word}'")
x = word_to_one_hot(word, vocab_size, word_to_ix)


h = np.dot(W_hh, h) + np.dot(W_xh, x)

print(f"Hidden state after '{word}' (Final Hidden State):\n{h.T}\n")


print("Predicting next word using final hidden state...")


output_scores = np.dot(W_ho, h)


def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

prediction_probs = softmax(output_scores)


predicted_index = np.argmax(prediction_probs)
predicted_word = ix_to_word[predicted_index]

print(f"Output scores over vocabulary:\n{output_scores.T}")
print(f"\nProbability distribution:\n{prediction_probs.T}")
print(f"\nPredicted word (index {predicted_index}): {predicted_word}")
print(f"Actual target word: {target_word}")

Vocabulary (4 words): ['best', 'is', 'messi', 'the']
Word to Index: {'best': 0, 'is': 1, 'messi': 2, 'the': 3}

Processing sequence: messi is the
Target word: 'best'
Initial hidden state:
[[0. 0. 0. 0. 0.]]

Processing word: 'messi'
Hidden state after 'messi':
[[-0.10458696 -0.19936731 -0.06254328 -0.02804806 -0.08536691]]

Processing word: 'is'
Hidden state after 'is':
[[-0.29557349  0.08485126 -0.07730034  0.00339084 -0.02675319]]

Processing word: 'the'
Hidden state after 'the' (Final Hidden State):
[[ 0.16440635 -0.04243028 -0.00233541 -0.01850637  0.02633376]]

Predicting next word using final hidden state...
Output scores over vocabulary:
[[-0.00843863 -0.02166293 -0.0147099   0.00943791]]

Probability distribution:
[[0.2500845  0.24679908 0.24852106 0.25459535]]

Predicted word (index 3): the
Actual target word: best
